name: 'Gemini Kanban Integration'
description: 'Integrates Gemini AI with KanbanGemini to process GitHub issues'
inputs:
  gemini-api-key:
    description: 'API Key for Google Gemini (required unless install-workflows is true)'
    required: false
  gemini-model:
    description: 'Primary Gemini model (e.g. gemini-2.5-flash)'
    required: false
  gemini-fallback-models:
    description: 'Comma-separated fallback Gemini models'
    required: false
  gemini-retries:
    description: 'Retry count for Gemini API calls'
    required: false
  github-token:
    description: 'GitHub Token (required)'
    required: true
    default: ${{ github.token }}
  install-workflows:
    description: 'Whether to install or update the Kanban workflows in the target repository (default: false)'
    required: false
    default: 'false'
  debug:
    description: 'Enable debug logging'
    required: false
    default: 'false'
  kanban-columns:
    description: 'Comma-separated list of Kanban column names (e.g., 'Backlog,Todo,In Progress,Done')'
    required: true
    default: 'Todo,In Progress,Done'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install action dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Run action
      run: node action.js
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
        INPUT_GEMINI_MODEL: ${{ inputs.gemini-model }}
        INPUT_GEMINI_FALLBACK_MODELS: ${{ inputs.gemini-fallback-models }}
        INPUT_GEMINI_RETRIES: ${{ inputs.gemini-retries }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_INSTALL_WORKFLOWS: ${{ inputs.install-workflows }}
        INPUT_DEBUG: ${{ inputs.debug }}
